---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - "npm config set spin false"

install:
  - npm install

script:
  - npm test
